name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Navigate to repository root
        run: cd ${{ github.workspace }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install
        working-directory: ./batalha-da-costa
      
      - name: Set environment variables
        run: |
          echo "VITE_FIREBASE_COLLECTION_1=${{ secrets.VITE_FIREBASE_COLLECTION_1 }}" >> .env
          echo "VITE_FIREBASE_COLLECTION_2=${{ secrets.VITE_FIREBASE_COLLECTION_2 }}" >> .env
          echo "VITE_FIREBASE_TYPE=${{ secrets.VITE_FIREBASE_TYPE }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_PRIVATE_KEY_ID=${{ secrets.VITE_FIREBASE_PRIVATE_KEY_ID }}" >> .env
          echo "VITE_FIREBASE_PRIVATE_KEY=${{ secrets.VITE_FIREBASE_PRIVATE_KEY }}" >> .env
          echo "VITE_FIREBASE_CLIENT_EMAIL=${{ secrets.VITE_FIREBASE_CLIENT_EMAIL }}" >> .env
          echo "VITE_FIREBASE_CLIENT_ID=${{ secrets.VITE_FIREBASE_CLIENT_ID }}" >> .env
          echo "VITE_FIREBASE_AUTH_URI=${{ secrets.VITE_FIREBASE_AUTH_URI }}" >> .env
          echo "VITE_FIREBASE_TOKEN_URI=${{ secrets.VITE_FIREBASE_TOKEN_URI }}" >> .env
          echo "VITE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.VITE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}" >> .env
          echo "VITE_FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.VITE_FIREBASE_CLIENT_X509_CERT_URL }}" >> .env
          echo "VITE_FIREBASE_UNIVERSE_DOMAIN=${{ secrets.VITE_FIREBASE_UNIVERSE_DOMAIN }}" >> .env

      - name: Build Vue app
        run: npm ci && npm run build
        working-directory: ./batalha-da-costa

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          repoToken: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
          projectId: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          firebaseServiceAccount: $${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEPLOY }}
          channelId: live
          entryPoint: ./batalha-da-costa